name: Earthly test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: all
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.0
      - uses: supabase/setup-cli@v1
        with:
          version: 1.46.5

      - run: earthly +setup-env
      - run: earthly +dev
      - run: docker restart supabase_rest_tet
      - run: earthly +test

