name: Conversion des markdowns

on:
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  update-json:
    name: Lecture et conversion des fichiers Markdown en JSON
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.0
      - uses: supabase/setup-cli@v1
        with:
          version: 1.52.3

      - name: Convertit les fichiers Markdown en JSON
        run: earthly +business-parse

      - name: Setup le projet
        run: earthly +setup-env

      - name: Lance le projet
        run: earthly +dev

      - name: Lance les tests business
        run: earthly +business-test

      - name: Commit les fichiers JSON
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Contenus json générés depuis les Markdowns
